Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {
    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();
      
      var builder = new DbContextOptionsBuilder<FactoryContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.Machines = new HashSet<EngineerMachine>();
    }
  

  public int EngineerId { get; set; }
  public string EngineerName { get; set; }
  
  public ICollection<EngineerMachine> Machines {get;}
  
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int MachineId { get; set; }
    public int EngineerId { get; set; }
    public Engineer Engineer { get; set; }
    public Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models{
  public class FactoryContext : DbContext{
    public DbSet<Engineer> Engineers {get; set;}
    public DbSet<Machine> Machines {get; set;}
    public DbSet<EngineerMachine> EngineerMachine {get; set;}
    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.Engineers = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    public string MachineName { get; set; }
    public ICollection<EngineerMachine> Engineers { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Engineer> engineerList = _db.Engineers.ToList();
      return View(engineerList);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);

    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if(MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId});
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = engineer.EngineerId});
    }
    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = joinEntry.EngineerId});
    }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Machine> machineList = _db.Machines.ToList();
      return View(machineList);
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include( machine => machine.Engineers)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId ==id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId ==id);
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId ==id);
      return View(thisMachine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId ==id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId ==id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if(EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine(){ EngineerId = EngineerId, MachineId = machine.MachineId});
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.MachineId});
    }
  }  
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
<h2>Add a machine for : @Html.DisplayFor(model => model.EngineerName)</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Add a machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" class="btn btn-default" />
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a new Engineer</h2>

@using (Html.BeginForm())
{
  @Html.Label("Engineer Full Name")
  @Html.TextBoxFor(model => model.EngineerName)

  @* @Html.Label("Engineer Specialty/Field")
  @Html.TextBoxFor(model => model.EngineerField) *@

  <input type="submit" value="Add Engineer" class="btn btn-default" />
}

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Delete this Engineer?</h2>
<hr/>
<p>Engineer Name: @Html.DisplayFor(model => model.EngineerName) </p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

<p>@Html.ActionLink("Back to Engineer List", "Index")</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.EngineerName) </h3>
@* <h4> Specialty: @Html.DisplayFor(model => model.EngineerField) </h4> *@

@if(@Model.Machines.Count == 0)
{
  <p>This Engineer does not currently have any Machines assigned to them</p>
}
else
{
  <h4>Machines:</h4>
  <ul>
    @foreach (var join in Model.Machines)
    {
        <li>@join.Machine.MachineName</li>
        @using (@Html.BeginForm("DeleteMachine", "Engineer"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" />
        }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Machine to an Engineer", "AddMachine", new {id = Model.EngineerId})</p>
<p>@Html.ActionLink("Edit Engineer Details", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit </h2>
<hr/>
<h2> Edit Engineers: @Html.DisplayFor(model => model.EngineerName)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)

  @* @Html.LabelFor(model => model.EngineerField)
  @Html.EditorFor(model => model.EngineerField) *@

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Engineer List", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Engineer Directory</h1>

@if (@Model.Count == 0)
{
  <h3>This Factory currenly has no Engineers....who's running the place?</h3>
}

@foreach (Engineer engineer in Model)
{
  <ul>
    <li>@Html.ActionLink($"{engineer.EngineerName} ", "Details", new { id = engineer.EngineerId }) </li>
  </ul>
}

<p>@Html.ActionLink("Add a new Engineer", "Create")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Clinic</h1>
<h3>@Html.ActionLink("View all Engineers", "Index", "Engineers")</h3>
<h3>@Html.ActionLink("View all Machines", "Index", "Machines") </h3>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a Engineer for : @Html.DisplayFor(model => model.MachineName)</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Add engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" class="btn btn-default" />
}

Factory/Views/Machines/Create.cshtml
  
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a new Machine</h2>

@using (Html.BeginForm())
{
  <p>
  @Html.Label("Full Name:")
  @Html.TextBoxFor(model => model.MachineName)
  </p>
  @* <p>
    @Html.Label("Date of Next Appointment:")
    @Html.TextBoxFor(model => model.AppointmentDate, new { @type = "datetime-local" })
  </p> *@
  @* <p>
    @Html.Label("Appointment is with:")
    @Html.DropDownList("DoctorId")
  </p> *@
  <p>
  <input type="submit" value="Add new Machine" class="btn btn-default" />
  </p>
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this Machine?</h2>
<hr/>
<p>Machine Name: @Html.DisplayFor(model => model.MachineName)</p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<p>@Html.ActionLink("Back to Machine List", "Index")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.MachineName) </h3>

@if(@Model.Engineers.Count == 0)
{
  <p>This Machine is not seeing any Engineers.</p>
}
else
{
  <h4>Engineers:</h4>
  <ul>
  @foreach (var join in Model.Engineers)
  {
    <li>@join.Engineer.EngineerName</li>
    @using (@Html.BeginForm("DeleteEngineer", "Patients"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete" />
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add Engineer", "AddDoctor", new {id = Model.MachineId})</p>
<p>@Html.ActionLink("Edit Machine Details", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>
<hr/>
<h2>Edit this Machine: @Html.DisplayFor(model => model.MachineName) </h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)
  <p>
    @Html.Label("Machine Name")
    @Html.EditorFor(model => model.MachineName)
  </p>
  @* <p>
    @Html.Label("Date of Next Appointment:")
    @Html.TextBoxFor(model => model.AppointmentDate)
  </p> *@
  <p>
  <input type="submit" value="save" />
  </p>
}

<p>@Html.ActionLink("Back to Machine List", "Index")</p>

Factory/Views/Machines/Index.cshtml
  
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machine Directory</h1>

@if (@Model.Count == 0)
{
  <h3>There are currently no machine in the factory database system.</h3>
}

<ul>
@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId });
   </li>
}
</ul>

<p>@Html.ActionLink("Add a new Machine", "Create")</p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dr.SillyStringz Corp.</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <link rel='stylesheet' href="~/css/styles.css" type="text/css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav">
        <a class="nav-item nav-link active text-light" href="/">Home</a>
        <a class="nav-item nav-link text-light" href="/machines">Machine Directory</a>
        <a class="nav-link nav-link text-light" href="/machines/create">Add a new Machine</a>
        <a class="nav-item nav-link text-light" href="/engineers">Engineer Directory</a>
        <a class="nav-item nav-link text-light" href="/engineers/create">Add a new Engineer</a>
      </div>
    </nav>
    <div class="container">
      @RenderBody()
    </div>
  </body>
</html>